set-w -g mode-keys vi
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm-256color:RGB"
set -g focus-events on
set -sg escape-time 10
set -g mouse on
set -s set-clipboard on
set -g allow-passthrough on
